### ISSUE TITLE
HTTPS Everywhere Feature

### ISSUE THREAD

**Issue by Manouchehri** [julian-klode/dns66#27]
This project seems like the perfect place to implement a HTTPS Everywhere type feature for Android. Thoughts?

**Comment by julian-klode** [comment]
No sorry, that's out of scope. We're filtering at a completely different, far lower level. DNS66 never sees your http traffic, so it can't redirect it to https. It's theoretically possible to do this though, but that would have a really big impact on performance and battery life.

But unfortunately it's not possible to combine two VPN services so that could be implemented as a different app and than used together with DNS66 :(

So maybe if we get some kind of plug-in infra, DNS66 could support crazy stuff like this in a clean, optional manner.

**Comment by julian-klode** [comment]
Adding the wontfix label now for the near term future, but might revise that at some point :)

**Comment by joshp23** [comment]
this might be the right place...
what about implementing dns over https?

**Comment by Manouchehri** [comment]
Given that Chrome is starting to aggressively push HTTPS over HTTP, I don't see a need for this anymore.
