### ISSUE TITLE
Google Translate Offline File Download Fails

### ISSUE THREAD

**Issue by gnr8shn** [julian-klode/dns66#300]
Lineage 14.1-2018-07-08-NIGHTLY-suzuran
E5823 Sony Experia Compact Z
Android 7.1.2
Android patch level 5th June 2018
DNS66 0.5.8

Downloading offline translation files fails on "Starting download". Stopping DNS66 and restarting download and or works.

**Comment by frdesfgddff** [comment]
The problem isn't with DNS66 per se, it is a problem with one of the filters. Offline language packs appear to be treated as adverts. The sensible solution would be to white list the app Google Translate in DNS66 - it doesn't show adverts.

If you go to the forums for Google translate, it is a common problem for people to be unable to download offline translation packages, and or seems that most of the time this is because an ad blocker is preventing the download from happening.

**Comment by gnr8shn** [comment]
Thanks I should've thought of that.

**Comment by frdesfgddff** [comment]
I'm not sure this should be closed; it is an option for the developer to automatically white list Google Translate in the list of allowed apps. I only added my comment when marking my issue a duplicate of this one, but the issue still exists. If the developer doesn't think this is the right solution they can can close this.
