### ISSUE TITLE
[FEATURE REQUEST] Must needed features

### ISSUE THREAD

**Issue by jerryn70** [julian-klode/dns66#32]
Ads are blocking successfully, Now it needs some options like, 
● different types of filters.
● whitelist option, for whitelisting (particular apps and sites/domains.)
● ad block count,.
● firewall and malware protection.
● One tap button to activate and deactivate.
● advance protection option to block youtube and similar site ads etc. 
● And simple UI like adclear.

**Comment by julian-klode** [comment]
This is not an actionable issue and should be split up into multiple actionable ones. In fact, you are contradicting your self: You cannot have all those features "And simple UI like adclear."

The UI currently is extremely simple. That said, it's not easy to understand in all cases, as it is a very simple mapping to the configuration.

●  different types of filters.

We have allow/deny/ignore filters for hosts. Filtering of IP (blocks) is tracked in #28 

●  whitelist option, for whitelisting (particular apps and sites/domains.)

You can whitelist sites host names right now, and #24 tracks support for listing multiple hosts in one entry. There's no support for domains though. We could implement that in a very crude way by allowing you to blacklist **.example.com and then for an URL like a.b.c.example.com  check
a.b.c.example.com, )(**a.b.c.example.com), **.b.c.example, **.c.example, **.example.com. As you can see, that introduces as many additional checks per hosts as there are dots in the name. (#33)

App whitelisting is a usable suggestion, that's very easy to implement (#34)

● ad block count

I know. Right? I had that one. It's not that easy though. Adding the count to the start page and automatically updating it would eat a lot of resources.That's why I thought about a Statistics page or something. (#35)

● firewall and malware protection.

The default hosts files should protect against malware. Firewall is #30.

● One tap button to activate and deactivate.

Not sure what you mean. We can't just simply allow people to click shortly on it and enable/disable the service this way, otherwise this happens far too often by accident.

● advance protection option to block youtube and similar site ads etc. 

I don't think that's possible with the chosen model. I'm not going to stop anyone from working on it and proposing a clear pull request, though.

● And simple UI like adclear.

The UI is extremely simple right now (it's just two lists after all). But with every feature we add it will get more complicated.

So, I opened actionable bugs #33, #34, and #35, and am going to close this one, as a meta wishlist style bug is nothing that can be reasonably worked with.
