### ISSUE TITLE
Whitelist *.example.com

### ISSUE THREAD

**Issue by Zehirmahn** [julian-klode/dns66#342]
Hi, I want to whitelist *s.youtube.com to make the video historic work in YouTube Vanced.
I tried to create a new filter and put *s.youtube.com in the location field and select Allow but it doesn't do the trick. Is this the proper way to whitelist?

**Comment by JakeHadley** [comment]
@Zehirmahn if you're gonna close an issue, could you at least put something in saying what you did to resolve your issue so the rest of us noobs can profit off of your ingenuity?

**Comment by Zehirmahn** [comment]
Youtube history works fine now.
Maybe 6 years ago I found another Youtube-specific way to deal with history (like Vanced + bypass DNS66).

The * trick doesn't seem to work (I tested with t.co which I whitelist, *.co doesn't do anything).
If I found a way to make it work I would have shared. I think I closed it to not bother Julian.

Sorry for the inconvenience.

**Comment by JakeHadley** [comment]
Wow dang you're still around on GH that's awesome haha. Yeah, no problem. I installed Revanced literally today and get a thing every time I open youtube fresh saying that "history is not being saved. This most likely is caused by a DNS ad blocker or network proxy", the only thing I got running is dns66, so I figured that was the culprit. 

So is there a way to whitelist domains in dns66? I'd be happy to try it on my end since you're saying it doesn't seem to work, I just don't see anywhere in the app that I can do that, which is why I was hoping you figured something out so many moons ago.

**Comment by Zehirmahn** [comment]
Yeah I was surprised to get an email from this thread after 6 years haha.
To whitelist a single domain you can add a new entry in the HOSTS tab : instead of giving the URL of a file you just give the domain name (t.co or else) then click on the shield of the created entry until the shield is crossed (which means whitelist).

I can't reproduce your issue with Revanced v20.07.39 with patches v5.18.0 and a fresh install of DNS66 v0.6.8 from the F-Droid store.
I can only advise to go to DNS66 APPS tab and make sure Revanced is checked there (which means it bypasses DNS66).

Do you have your Google account working inside Revanced? The app microG services should have been installed by Revanced. If not it is available here https://github.com/ReVanced/GmsCore/releases
and battery optimization should be disabled for this app. I didn't need to change a single other setting.

Edit : Maybe you need to select the GmsCore patch when patching Youtube
