### ISSUE TITLE
Support IPv6 DNS servers

### ISSUE THREAD

**Issue by julian-klode** [julian-klode/dns66#4]
The app currently cannot talk to IPv6 servers or emulate them.

**Comment by jerryn70** [comment]
When I use XDA labs and some other apps it take extra time to load the page, comparing with the loading speed without vpn. 

Example : without vpn, XDA labs takes 10 seconds to load the page content. 
with vpn it takes about 25 seconds .

this problem  occurs only when using wifi . 
On mobile data there is no change. And browsers didn't show any slow downs in both wifi and mobile data.

All this issue is related to ipv6 ? I'm i correct ?

**Comment by FernandoMiguel** [comment]
i would say it is very probable

**Comment by julian-klode** [comment]
I set up my IPv6 tunnel and worked on this for a few hours today, and am happy to confirm that IPv6 now seems to work perfectly fine. So, this will be solved in 0.4.

**Comment by thekyriarchy** [comment]
thank you!!!
