### ISSUE TITLE
Constant refresh hosts warning on 7.1.1

### ISSUE THREAD

**Issue by jb0nez** [julian-klode/dns66#43]
Nexus 5x, 7.1.1 DP2, tho it happened with DP1. DNS66 will always report the host files need to be downloaded when turning on. Refresh and I see the downloads happening in notifications. Press on, same message.
Most ads are being blocked though fortunately.

**Comment by julian-klode** [comment]
As I just wrote on xda, this is kind of weird. If all the downloads completed successfully, it should work. Sometimes some host files are unreachable in which case it may hang.

YOu might want to look at a logcat of starting the service and see which files it can't load (it will try all after you allow it to contineu in the popup).

**Comment by jb0nez** [comment]
Well after an unrelated issue I had to factory reset. Also did a flash of factory image of Dp2. No problems now, it appears that all is working as it should. I did switch to ES Downloader before testing, but it appears that DNS66 uses the Android download manager anyway. And no problems downloading hosts now.

**Comment by z751** [comment]
I also encountered this as well when I upgraded from version 0.1.3 to version 0.2.0. 

Also I am not 100% sure on this but I think it would also try to keep downloading the files after I left the app.  I saw the download notification go on but it vanished before I could see which app it was.  This happened I would say like every 2 or 3 minutes.

However, I have uninstalled the app, and installed the version 0.2.0 directly and both of these problems seem to have been fixed.

**Comment by julian-klode** [comment]
Sure it will try downloading it from time to time, independent of the app. The system-wide download manager is responsible for downloading files, not the app.

**Comment by julian-klode** [comment]
I also encounter warnings from time to time, but not sure why.

**Comment by z751** [comment]
So today I downloaded the updated hosts files and got the error again.

**Comment by julian-klode** [comment]
The thing with downloading is: I have to delete the old file first right now, as the downloader does not replace existing files, but appends stuff to the filename. I should change that to download to a temporary file name and then replace the real file atomically, but that is somewhat harder to do, so that's why I chose the current way as a first step.

Today I noticed that something on my phone deleted all my hosts files, I'm not sure why...

**Comment by Zazie-Lavender** [comment]
having this issue myself since I installed this app. I end up forcing it to refresh the hosts several times before it takes. Also seems to choke hard on downloading multiple files

**Comment by greckzero** [comment]
Testing out, and i've found in LogCat what appears when the app try to download the files:
System - ClassLoader referenced unknown path: /system/framework/tcmclient.jar
DownloadManager - [220] Stop requested with status HTTP_DATA_ERROR: Connection refused
DownloadManager - [220] Finished with status HTTP_DARA_ERROR

Using Android 7.1.1 too

**Comment by axzxc1236** [comment]
This "constant refresh hosts warning" issue is happening on my Android too.
But I am using Android 6.0.1 and DNS66 v0.3.0.
Looks like refresh is broken, and not hosts file are actually being downloaded, I tried to reboot my Android but it doesn't help.

**Comment by julian-klode** [comment]
This will be fixed in 0.5 which completely changes the backend from a list of files to an SQLite database. 

Files will now be read directly from the web server in the app, and directly inserted into the database.
If a file has errors, it will not be updated (and not removed like before; host file updates are now atomic).

This will also optionally happen automatically periodically in the background, as specified in #2.
