### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by mr-gosh** [julian-klode/dns66#6]
Is the application GPL or Apache licensed?
Is there a formerly version that still is licensed unde an apache or mit license?

We could possibly commit stuff than... thats why i ask

**Comment by julian-klode** [comment]
The copyright file clearly states what is what. Tje vpn subpackage is GPL3 (it contains parts of a project without an or-later clause...), some icons taken from Google are Apache, and the rest (what I wrote) is GPL3 or newer.

I'd love to relicense (Apache) or add an exception to the GPL so I can distribute the app via Amazon at some point (more users, easier access). But that requires consent from @dbrodie who wrote the original implementation of the vpn subpackage (in his dbrodie/AdBuster).

Optimally we'd have GPL-3+ for the entire code with a licence exception like this:

"As a special exception, an application distribution service provider

**Comment by julian-klode** [comment]
Sorry, accidentally closed the issue because I was writing on my phone:

"As a special exception, an application distribution service provider such as Amazon, may modify an .apk provided to it for inclusion in their application distribution program to the extend necessary to include the code in their application distribution program.".

The thing with Amazon is: They modify the apk to include analytics code. Now, I'm not a big fan of this, but Amazon will reach a lot more people than f-droid.

**Comment by julian-klode** [comment]
If you are confused about the other Apache and MIT mentions in the README file: The gradle build file references several other libraries (mostly Android, but also pcap4j, dnsjava, and ahbottomnavigation), so I noted their license in the README.md file to make sure everyone knows what they are.

I guess for contributing easily I could say the following. Let me know if that sounds fair to you, I don't know.

Licensing of contributions
----------------------------------
Contributions should be generally GPL-3+, unless modifying one of the Apache licensed files mentioned in the copyright file. There might be exceptions, for example, if you want to contribute a code snippet from an Apache licensed project.

As we are currently still evaluating a relicensing to allow the app to be included in the Amazon app shop, so we ask you to grant us the permission to

(1) relicense your work under the GPL 3 or later with an exception permitting binary modification by Amazon (and other app shop providers).

(2) relicense your work under the terms of the Apache License, version 2, if all other code in the project gets relicensed to Apache.

If you agree with those contribution terms, please state so in your pull request that you do so, for example, by including:

"I agree with the contribution terms."

in the pull request message.

**Comment by julian-klode** [comment]
@mr-gosh So, I had some contact with dbrodie, and it seems like he does not want Apache, but is happy with the vpn/ part as GPL-3+. Still nothing new WRT an exception for Amazon publishing.

And you might say: Hey, there are already GPL apps on the App Shop. And you're right. But:

In Distribution schedule, section 3a it says:
"You also hereby grant us the nonexclusive, irrevocable, royalty-free, worldwide right to [...] (iii) modify and add to your Apps so that we can collect analytics relating to the Apps, evaluate and enforce our Program policies, and share aggregated information with you and others regarding the Program"

And section 4, Additional Distribution Terms states:
"c. Prohibited Actions. You have not and will not submit any Content that contains any software or other materials that are subject to licenses or restrictions (e.g., open source software licenses) that, when combined with additional software or other materials (collectively "additional items"), would require us to disclose, license, distribute or otherwise make all or any part of such additional items available to anyone."

So, submitting a GPL app without an exception would be a breach of that agreement. 

And I think it's kind of worthwhile to have the app there as well, having it just on f-droid is *very* niche.

**Comment by julian-klode** [comment]
I guess it might make sense to just make all icons Apache licensed instead of just the ones imported from Google. That will then give us an end result where icons are Apache licensed and everything else is GPL-3+, which is probably a lot easier for people (and then I can rename LICENSE.Apache-2.0 to LICENSE.icons).
