### ISSUE TITLE
DNS66 breaks IPv6 connectivity

### ISSUE THREAD

**Issue by Angristan** [julian-klode/dns66#68]
Without DNS66 : 
![screenshot_20161228-150356](https://cloud.githubusercontent.com/assets/11699655/21524362/cc502124-cd15-11e6-9b9d-fd383e133955.png)
With :
![screenshot_20161228-150451](https://cloud.githubusercontent.com/assets/11699655/21524367/d18adfee-cd15-11e6-9ab8-e9d79a3fc83b.png)

**Comment by julian-klode** [comment]
That's tracked in #4

**Comment by Angristan** [comment]
I saw it, but it thought is was only related to IPv6 DNS servers, not IPv6 connectivity.

**Comment by julian-klode** [comment]
I set up my IPv6 tunnel and worked on this for a few hours today, and am happy to confirm that ipv6-test.com now works correctly with the merge of the ipv6 branch. So, this will be solved in 0.4.

**Comment by thekyriarchy** [comment]
can't wait! is there an ETA?

**Comment by julian-klode** [comment]
I'm trying to get the hostdb branch working first. That fails to reconnect properly - apparently there's an issue if reconnects are really fast instead of slow (just spent 6 hours on this today without a result). Also waiting for F-Droid to build things again, so probably somewhere between tomorrow and end of next week.
