### ISSUE TITLE
won't reconnect automatically on network re–connection 

### ISSUE THREAD

**Issue by alekksander** [julian-klode/dns66#83]
app won't do it's magic without manually pressing the big power button. is this behavior desired? happens both on wifi and lte

**Comment by julian-klode** [comment]
It should automatically reconnect. It might get confused after some time, in which case a logcat would be helpful (or generate a bug report with an option in your phone's developer options, if that's available) :)

You likely want to send this in private, not in public - it contains hostnames resolved amongst debugging output from other system parts.

**Comment by alekksander** [comment]
i'll try to remember next time when it occurs, because now after phone reboot it has corrected itself

**Comment by arynadam** [comment]
I think I have a similar problem.
I cant access internet while DNS66 is active and wifi is running fine. Tried restarting DNS66 and rebooting the phone, nothing changed. Below is the logcat for my attempt to access github.com, as you can see it timeouts immediately.

I am using custom DNS servers (Google DNS). Disabling them didnt change anything...
Iam still getting "DNS_PROBE_FINISHED_NO_INTERNET" in Chrome and no connection in other apps as well.

After connecting to different router it seems it fixed itself. I will try to repeat the problem.

02-20 22:51:07.993  7645  7720 D AdVpnThread: doOne: Polling 130 file descriptors: org.jak_linux.dns66
02-20 22:51:08.043  7645  7720 D AdVpnThread: Read from device: org.jak_linux.dns66
02-20 22:51:08.043  7645  7720 D AdVpnThread: handleDnsRequest: Incoming packet to 192.0.2.4 AKA 2 AKA /8.8.8.8: org.jak_linux.dns66
02-20 22:51:08.043  7645  7720 I AdVpnThread: handleDnsRequest: DNS Name github.com Allowed, sending to /8.8.8.8: org.jak_linux.dns66
02-20 22:51:08.053  7645  7720 D AdVpnThread: removeEldestEntry: Removing entry due to reason timeout=true, overflow=false: org.jak_linux.dns66
02-20 22:51:08.053  7645  7720 D AdVpnThread: doOne: Polling 130 file descriptors: org.jak_linux.dns66
02-20 22:51:08.053  7645  7720 D AdVpnThread: Read from device: org.jak_linux.dns66
02-20 22:51:08.053  7645  7720 D AdVpnThread: handleDnsRequest: Incoming packet to 192.0.2.4 AKA 2 AKA /8.8.8.8: org.jak_linux.dns66
02-20 22:51:08.053  7645  7720 I AdVpnThread: handleDnsRequest: DNS Name accounts.google.com Allowed, sending to /8.8.8.8: org.jak_linux.dns66
02-20 22:51:08.053  7645  7720 D AdVpnThread: removeEldestEntry: Removing entry due to reason timeout=true, overflow=false: org.jak_linux.dns66
02-20 22:51:08.053  7645  7720 D AdVpnThread: doOne: Polling 130 file descriptors: org.jak_linux.dns66
02-20 22:51:08.053  7645  7720 D AdVpnThread: Read from device: org.jak_linux.dns66

**Comment by julian-klode** [comment]
@arynadam You are not getting any response from the upstream DNS server as far as I can tell. The logcat is too short to say that conclusively, but 130 file descriptors and entries being removed due to timeouts makes it very likely.

**Comment by alekksander** [comment]
it doesn't connect correctly after a while (after lets say a day, i can see it gets stuck in reconnecting state).
it happens commonly. will generate a log for You soon.

**Comment by julian-klode** [comment]
I'll likely completely rework the whole connection event loop in 0.5, so I'd hope that fixes it.

**Comment by julian-klode** [comment]
Should be "fixed" (to the extent possible) by adding a watchdog in d4dbe995fd755120bc5fc72c4fb9f2ba372904c1
