### ISSUE TITLE
Reconnecting error

### ISSUE THREAD

**Issue by ancaemanuel** [julian-klode/dns66#9]
http://m.imgur.com/7jgY019
Not sure about it, just reporting. To let you know.

**Comment by julian-klode** [comment]
Thanks. Did you move around, so it switched networks or something? You could try searching the logcat for output from AdVpnThread, but I'm not sure it contains anything useful:

I just had an even more crazy issue. I tried disconnecting and it basically disconnected and instantly reconnected, did that twice. After about 3 long presses it finally shut down, though. No errors in the logcat, though...

So, the whole thread tear-down logic is not really optimal yet. I should probably carefully read the code and see if I find out what could be wrong here.

**Comment by julian-klode** [comment]
This might be fixed in [version 0.1.1](https://github.com/julian-klode/dns66/releases/tag/v0.1.1). 

There was a huge resource leak: We created sockets for connecting to the DNS servers for blacklisted hosts, but never closed them. So once we reach a bit more than 4000 blocked sites, we would run out of file descriptors and could not create any new connections. In 0.1.1 it only opens a socket now when it actually sends data to the DNS server.

I also fixed several other smaller bugs related to stopping and restarting of the service.

**Comment by julian-klode** [comment]
It seems to run stable these days, so I'm closing this for now. If you can reproduce the issue in 0.1.1 or 0.1.2, feel free to reopen it.

**Comment by tburn76** [comment]
Im currently getting this error in 0.1.2 How can I upload logs or something?

**Comment by tburn76** [comment]
I reinstalled the app which didn't fix the issue.

**Comment by iamalwayslate** [comment]
Just installed the app. There is a reconnecting issue. I don't know what is causing this. Although my Wi-Fi is stable.

**Comment by rraallvv** [comment]
I'm having this issue with DNS66 0.6.1 on Android Lollipop 5.0.1

**Comment by racuna** [comment]
I have a problem like this as well:
MIUI 11.0.3 stable (Android 9), with DNS66 version 0.6.5
