### ISSUE TITLE
Images Loading Slowly

### ISSUE THREAD

**Issue by Trooper27** [julian-klode/dns66#97]
Hi,

Just joined up here since I use and love your app so much.  I have noticed (not sure if anyone else has posted this yet) that in the newest version of DNS66 0.4.0 that images and media are slow to load. This is both on Wifi and LTE data.  I noticed it in all of my Reddit apps as well as YouTube.

I uninstalled and went back to 0.3.1 and everything seems to be back to normal.

Thanks!

**Comment by julian-klode** [comment]
DNS66 does not affect your connection speed, it only affects DNS queries. 0.4 introduced support for IPv6 DNS servers. The issue here is probably just that your IPv6 connectivity is slower, or you have no real IPv6 connectivity, but IPv6 DNS servers, and the browser first tries to connect to IPv6, but that fails. All other changes were UI-only.

**Comment by Trooper27** [comment]
Hi Julian,

Thanks for getting back to me.  I hear you on speed and it is likely the latter (as in, I do not have IPv6 as of yet.).  Will stick with the older version for now.

Cheers!

**Comment by julian-klode** [comment]
@Trooper27 Starting with 0.5.0 RC1, you can disable IPv6 support. It also has a few new features (like local file support), and a brand new UI: https://forum.xda-developers.com/showpost.php?p=71930963&postcount=495
