### ISSUE TITLE
Lookout VPN Virus/Web Scan

### ISSUE THREAD

**Issue by nobeguy** [julian-klode/dns66#98]
I use Lookout Safe Browsing VPN connector for web browsing. If DNS66 is active and go open a website I get a request to close DNS66 VPN to allow Lookout Safe Browsing virus scan VPN. Should I be concerned?

**Comment by julian-klode** [comment]
There can only be a single VPN service active in Android, so in order to enable DNS66, which uses a VPN service to enable it to set DNS servers, Android needs to turn off any other VPN service. So you need to choose one.

I can only strongly recommend not using stuff like VPN- and browser based virus scanners, as these types of services often have massive security issues. 3 years ago, German computer magazine c't tested apps like that and found that they send the URLs of all visited webpages, most unencrypted (!!!), to the servers of the "anti virus" providers - out of 6 services tested, only one got a positive review, and that was not Lookout. Ultimately, Anti Virus is mostly a scam, and web browser addons are a way for the companies to collect user history that they can use and potentially sell to third parties.

It's ultimately your decision, though.

**Comment by nobeguy** [comment]
Thanks for the prompt response Julian! It's greatly appreciated.
